version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - devops-network

  # Backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - FRONTEND_URL=http://localhost:3000
      - MONGODB_URI=mongodb://mongo:27017/devops-dashboard
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRE=30d
      - JWT_COOKIE_EXPIRE=30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.kube:/root/.kube
    depends_on:
      - mongo
    networks:
      - devops-network

  # MongoDB service
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - devops-network

networks:
  devops-network:
    driver: bridge

volumes:
  mongo-data:
